#%RAML 1.0 NamedExample
value:
  -
    id: 1
    type: home
    street: liverpool
    unit: 12-c
    city: texas
    state: houston
    zipcode: 6045
  -
    id: 2
    type: office
    street: seatle
    unit: 13-c
    city: illinois
    state: toronto
    zipcode: 6000